title: Natan Fernandes
tagline: A site dedicated to showcase my content
description: >
I'm Natan, a Software Developer based in Brasilia-DF, Brazil.
Currently working as a freelancer. Feel free to get in touch with me and explore some of my projects and content! â¤ï¸
url: https://natanfernandesdev.github.io
author: Natan Fernandes
twitter:
  username: 
  card: 
social:
  name: Ben Balter
  links:
    - https://github.com/natanFernandesDev/
    - linkedin.com/in/natan-fernandes-209586185/
    - https://medium.com/@natangt11
locale: en_US

theme: jekyll-theme-console

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

header_pages:
  - index.md
  - projects.md
  - articles.md
  - contact.md

footer: 'Made with <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> ğŸ§ª and <a href="https://github.com/b2a3e8/jekyll-theme-console" target="_blank">Console Theme</a> ğŸ¨'

exclude:
  - README.md
  - LICENSE